In [1]:
def listSkills(val, list=[]):
    list.append(val)
    return list

list1 = listSkills('NodeJS')
list2 = listSkills('Java', [])
list3 = listSkills('ReactJS')
print("%s" % list1)
print("%s" % list2)
print("%s" % list3)

['NodeJS', 'ReactJS']
['Java']
['NodeJS', 'ReactJS']


In [2]:
import re
result = re.findall('Welcome to Turing', 'Welcome', 1)
print(result)

[]


In [2]:
x = 10
x = x+1
print (x)

11


In [10]:
sal = 35000
sal = sal+1000
print(sal)

36000


In [21]:
x = float(input("Enter value of x = "))
y = int(input("Enter value of y = "))
z = x+y
print('the sum of the two numbers is = ', z )

Enter value of x = 15.55555555555555555555555555555555555555555555555555555555555555555555555555
Enter value of y = 14
the sum of the two numbers is =  29.555555555555557


 Arithematic Operation 

In [23]:
x = float(input("enter the value of x = "))
y = float(input('enterthe value of y = '))
r1 = x+y
r2 = x-y
r3 = x*y
r4 = x/y
print("sum of the two numbers = " ,r1)
print ('difference in the two numbers = ', r2)
print('multiplication of the two numbers =' ,r3)
print('division of the two numbers =' ,r4)

enter the value of x = 45
enterthe value of y = 55
sum of the two numbers =  100.0
difference in the two numbers =  -10.0
multiplication of the two numbers = 2475.0
division of the two numbers = 0.8181818181818182


In [28]:
x=100
while x <=200:
    print(x)
    x = x+1
   
print('end')
    
    

100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
end


In [31]:
m = int(input('from the number = '))
n = int(input('to the number = '))
print('even numbers between the given numbers are')
print('-------------')

if m%2 !=0:
    m=m+1
else:
    m=m
    
while m<=n:
    print(m)
    m=m+2
    
print('-----The END ------')    


from the number = 12
to the number = 24
even numbers between the given numbers are
-------------
12
14
16
18
20
22
24
-----The END ------


 Reverse the number

In [54]:
num = int(input('Enter the number to be reversed = '))
while num !=0:
    reversedNumber = num%10
    print(reversedNumber, end='')
    num = int(num/10)
    
print(reversedNumber, end=' ')    

Enter the number to be reversed = 258963147
7413698522 

In [53]:
num = int(input('enter number to be summed by digit = '))
summ = 0
while num!=0:
    sum = num%10
    summ = summ + sum
    
    num = int(num/10)
print(summ)    

enter number to be summed by digit = 203
5


In [65]:
L =[2, 3, 5, 8, 15, 10, 96]
n = len(L)
i=0
r=0
while i<n:
    print(L[i])
    i =i+1

   

    

2
3
5
8
15
10
96


In [71]:
L =[2, 3, 5, 8, 15, 10, 96]
n = len(L)
i=0

sum = 0
while i<n:
    sum = sum + L[i]
    print(L[i])
    i =i+1
print('sum of all the list elements = '  , sum)

2
3
5
8
15
10
96
sum of all the list elements =  139


# To Display given string for  5 times - we will use wile loop

In [73]:
str = input ('Enter a String: ')
count = 1
while count<=5:
    print(str)
    count= count+1

Enter a String: what is your name : My name is Siddu
what is your name : My name is Siddu
what is your name : My name is Siddu
what is your name : My name is Siddu
what is your name : My name is Siddu
what is your name : My name is Siddu


### Display two sequences


In [226]:
i = 1; j =5
while i<=5:
    print(i,)
    print("------", j)
    i= i+1
    j= j-1

1
------ 5
2
------ 4
3
------ 3
4
------ 2
5
------ 1


In [78]:
i= 1
while i<=10:
    print(i)
    i=i+1

1
2
3
4
5
6
7
8
9
10


####  Displaying even Numbers from 100-200 with while LOOP

In [79]:
i= 100
while i<=200:
    print(i)
    i=i+2

100
102
104
106
108
110
112
114
116
118
120
122
124
126
128
130
132
134
136
138
140
142
144
146
148
150
152
154
156
158
160
162
164
166
168
170
172
174
176
178
180
182
184
186
188
190
192
194
196
198
200


#  FOR Loop

in for loop the sequence is executed as many time as there are iterations 
where as in while loop the code comes out when the condition is fulfilled


In [82]:
for i in range(10 ,20,2):
    print(i)

10
12
14
16
18


In [83]:
for i in range(100 ,201,2):
    print(i)

100
102
104
106
108
110
112
114
116
118
120
122
124
126
128
130
132
134
136
138
140
142
144
146
148
150
152
154
156
158
160
162
164
166
168
170
172
174
176
178
180
182
184
186
188
190
192
194
196
198
200


In [84]:
L = [1, 3, 2, 8, 16, 7, 3]

for i in L:
    print(i)

1
3
2
8
16
7
3


In [92]:
L = [1, 3, 2, 8, 16, 7, 3, 32, 0, 98]

for i in L:
    if i%2==0 and i!=0:
        print(i)
    
    

2
8
16
32
98


In [100]:
L = [1, 3, 2, 8, 16, 7, 3, 32, 0, 98]

max= L[0]
for i in L:
    if i>max : max =i
print(max)

98


In [103]:
roe = int(input('how many rows? '))
for i in range(1, roe+1):
    for j in range(1, i+1):
        print('* ', end= '')
        
    print()   

how many rows? 12
* 
* * 
* * * 
* * * * 
* * * * * 
* * * * * * 
* * * * * * * 
* * * * * * * * 
* * * * * * * * * 
* * * * * * * * * * 
* * * * * * * * * * * 
* * * * * * * * * * * * 


In [104]:
L = [1, 3, 2, 8, 16, 7, 3, 32, 0, 98, -88, -56, -83, -77]

sum1=0; sum2=0
for i in L:
    if i>0: sum1=sum1+i
    if i<0: sum2=sum2+i 
        
print('sum of positive numbers =', sum1)  
print('sum of negative numbers =', sum2) 
        

sum of positive numbers = 170
sum of negative numbers = -304


In [106]:
n = int(input('Enter a number to check if its prime Number : '))
flag = True
for i in range(2, n):
    if n%i ==0:
        flag = False
        break
        
if flag == True:
    print(n, 'is a Prime Number')
else:
    print(n, 'is not a Prime Number')


        
    
    
        

Enter a number to check if its prime Number : 37
37 is a Prime Number


## Print Prime Numbers between 100 to 200 ---- By self after106 execution


In [146]:
for i in range(100, 201):
    for k in range(2, i):
        if i%k==0:
            
            print(i, 'is not a Prime Number')
            break
        else:
            print(i, 'is a Prime Number')
            break
   


    

    

100 is not a Prime Number
101 is a Prime Number
102 is not a Prime Number
103 is a Prime Number
104 is not a Prime Number
105 is a Prime Number
106 is not a Prime Number
107 is a Prime Number
108 is not a Prime Number
109 is a Prime Number
110 is not a Prime Number
111 is a Prime Number
112 is not a Prime Number
113 is a Prime Number
114 is not a Prime Number
115 is a Prime Number
116 is not a Prime Number
117 is a Prime Number
118 is not a Prime Number
119 is a Prime Number
120 is not a Prime Number
121 is a Prime Number
122 is not a Prime Number
123 is a Prime Number
124 is not a Prime Number
125 is a Prime Number
126 is not a Prime Number
127 is a Prime Number
128 is not a Prime Number
129 is a Prime Number
130 is not a Prime Number
131 is a Prime Number
132 is not a Prime Number
133 is a Prime Number
134 is not a Prime Number
135 is a Prime Number
136 is not a Prime Number
137 is a Prime Number
138 is not a Prime Number
139 is a Prime Number
140 is not a Prime Number
141 is a Prime

In [148]:
for i in range(100, 201):
    for k in range(2, i):
        if i%k==0:
            
            break
        else:
            print(i, 'is a Prime Number')
            break
           

101 is a Prime Number
103 is a Prime Number
105 is a Prime Number
107 is a Prime Number
109 is a Prime Number
111 is a Prime Number
113 is a Prime Number
115 is a Prime Number
117 is a Prime Number
119 is a Prime Number
121 is a Prime Number
123 is a Prime Number
125 is a Prime Number
127 is a Prime Number
129 is a Prime Number
131 is a Prime Number
133 is a Prime Number
135 is a Prime Number
137 is a Prime Number
139 is a Prime Number
141 is a Prime Number
143 is a Prime Number
145 is a Prime Number
147 is a Prime Number
149 is a Prime Number
151 is a Prime Number
153 is a Prime Number
155 is a Prime Number
157 is a Prime Number
159 is a Prime Number
161 is a Prime Number
163 is a Prime Number
165 is a Prime Number
167 is a Prime Number
169 is a Prime Number
171 is a Prime Number
173 is a Prime Number
175 is a Prime Number
177 is a Prime Number
179 is a Prime Number
181 is a Prime Number
183 is a Prime Number
185 is a Prime Number
187 is a Prime Number
189 is a Prime Number
191 is a P

In [151]:
for num in range(100, 201):
    if all(num%i !=0 for i in range(2, num)):
        
        print(num, '  - is a Prime Number')
        

101   - is a Prime Number
103   - is a Prime Number
107   - is a Prime Number
109   - is a Prime Number
113   - is a Prime Number
127   - is a Prime Number
131   - is a Prime Number
137   - is a Prime Number
139   - is a Prime Number
149   - is a Prime Number
151   - is a Prime Number
157   - is a Prime Number
163   - is a Prime Number
167   - is a Prime Number
173   - is a Prime Number
179   - is a Prime Number
181   - is a Prime Number
191   - is a Prime Number
193   - is a Prime Number
197   - is a Prime Number
199   - is a Prime Number


In [154]:
s= '    sai vinay sunkara . s'
print(s.strip())

sai vinay sunkara . s


In [156]:
for i in s: 
    print(i)

 
 
 
 
s
a
i
 
v
i
n
a
y
 
s
u
n
k
a
r
a
 
.
 
s


In [157]:
print(s[0])

In [158]:
print(s[0:6])

    sa


In [160]:
print(s[ : -1])

    sai vinay sunkara . 


In [161]:
print(s[:7])

    sai


In [162]:
print(s[:-7])

    sai vinay sunk


In [163]:
print(s[4:-7])

sai vinay sunk


In [164]:
print(s[4:7])

sai


In [168]:
print(s[4:10:2])

siv


In [170]:
print(s[4:15:2])

sivnys


In [172]:
print(s[4:10:1])

sai vi


In [174]:
# to Accept id, name and salary

id = int(input('enter the id:'))
name = input('Enter your name : ')
salary = float(input(' enter your salary:'))
print('your id= {} \ nname ={} \ nsalary = {}'.format(id,name,sal))

enter the id:1616464964
Enter your name : sai vinay sunkara
 enter your salary:5600700
your id= 1616464964 \ nname =sai vinay sunkara \ nsalary = 36000


In [184]:
id = int(input('enter the id:'))
name = input('Enter your name : ')
salary = float(input(' enter your salary:'))
print('your id= {}\nname ={} / salary = {}'.format(id,name,sal))

enter the id:1361
Enter your name : dafhdiha
 enter your salary:3154
your id= 1361
name =dafhdiha / salary = 36000


### Enter Three Numbers Find their sum and average


In [188]:
a,b,c = [float(x) for x in input('enter 3 numbers: ').split()]
sum = a+b+c
average = sum/3

print("sum= %i\naverage= %8f" % (sum, average))



enter 3 numbers: 12 23 36
sum= 71
average= 23.666667


### Finding the area of the circle when entered raidius

In [192]:
r= float(input("enter the Radius of the Circle = "))
area = (22/7 * r**2)
print("Area of the circle is = " , area)

enter the Radius of the Circle = 12
Area of the circle is =  452.57142857142856


### Joining strings


In [196]:
s = input('Enter your first sentence: ')
t = input('Enter your second sentence: ')

print(s + t)

Enter your first sentence: hi 
Enter your second sentence: what are you
hi what are you


In [199]:
str1, str2 = input( ' enter your two strings: '). split(',')
print(' total strings: ', str1+str2)

 enter your two strings: hi buddy , call me
 total strings:  hi buddy  call me


### Enter a number and display its cube value

In [201]:
num = float(input( 'Enter your nuber to find its cube = '))
cube = num**3
print('cube of the given number is = ', cube)

Enter your nuber to find its cube = 2
cube of the given number is =  8.0


In [202]:
num = float(input( 'Enter your nuber to find its cube = '))
print('cube of the entered number is = ', num**3)

Enter your nuber to find its cube = 33
cube of the entered number is =  35937.0


### Sort a group of strings 



In [203]:
lst = []

n = int(input('how many strings?'))

for i in range(n):
    s = input('enter string:')
    lst.append(s)
    
lst.sort()
for i in lst:
    print(i)

how many strings?3
enter string:hello bolo
enter string:hello 
enter string:handerler
handerler
hello 
hello bolo


### sorting a group of strings - 2



In [206]:
lst=[]

n = int(input('how many strings you wish to sort ? '))

for i in range(n):
    s = input( 'Enter String: ')
    lst.append(s)
    
lst.sort()

for i in lst:
    print(i)

how many strings you wish to sort ? 3
 Enter String: hello
 Enter String: vinay 
 Enter String: siddu babu
hello
siddu babu
vinay 


### Enter a list of different elements and display them

In [210]:
# here we will be using eval()

lst = eval(input('enter a lst: '))
print('List= ', lst)
for i in lst:
    print(i)
    

enter a lst: 12, 22, 33
List=  (12, 22, 33)
12
22
33


In [211]:
lst = eval(input('enter a lst: '))
print('List= ', lst)
for i in lst:
    print(i)
    

enter a lst: hello, 22, 3@k, su12@123


NameError: name 'hello' is not defined

In [212]:
lst = eval(input('enter a lst: '))
print('List= ', lst)
for i in lst:
    print(i)

enter a lst: vinay, siddu, Ajju, Varshu


NameError: name 'vinay' is not defined

In [213]:
lst = eval(input('enter a lst: '))
print('List= ', lst)
for i in lst:
    print(i)

enter a lst: 1, vinay, 22


NameError: name 'vinay' is not defined

In [214]:
lst = eval(input('enter a lst: '))
print('List= ', lst)
for i in lst:
    print(i)

enter a lst: 1, 22, 33333
List=  (1, 22, 33333)
1
22
33333


### Test whether a given number is even or Odd

In [215]:
x = int(input(' Enter a number to check Even or Odd : '))
if x%2==0:
    print(x, 'is an Even Number')
else:
    print(x, 'is Odd Number')

 Enter a number to check Even or Odd : 23
23 is Odd Number


### showing if the given number is Even, Odd or Zero


In [220]:
x = int(input(' Enter a number to check Even or Odd : '))
if x==0:
    print(x, 'is zero')
elif(x%2==0):
    
    print(x, 'is Even number')
else:
    print(x, 'is Odd Number')

 Enter a number to check Even or Odd : 33
33 is Odd Number


In [223]:
# Version 2
x = int(input(' Enter a number to check Even or Odd : '))
if x==0:print(x, 'is zero')    
elif(x%2==0):print(x, 'is Even number') 
else:print(x, 'is Odd Number')
    

 Enter a number to check Even or Odd : 0
0 is zero


### Display Numbers from 1-10  using while loop

In [224]:
x=1
while(x<=10):
    print(x)
    x=x+1
    

1
2
3
4
5
6
7
8
9
10


In [225]:
# displaying End after the while looop exits

x=1
while(x<=10):
    print(x)
    x=x+1
    
print('END')    

1
2
3
4
5
6
7
8
9
10
END


In [234]:
x = int(input('enter the value of x: '))
i = x
while i<=x+100:
    print(i, j)
    i=j+1
    j=i+1
    

enter the value of x: 1
1 108


In [247]:
x = int(input('enter the value of x: '))
i =x

while i <= x+100 and i<=100:
    print(i)
    
    i = i+1
 


enter the value of x: 1
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


### Display even Numbers between m, n

In [249]:
m ,n  = [int(i) for i in input('enter start, stop: ').split(',')]
x=m
if x%2!=0: x=m+1
while(x<=n):
    print(x)
    x+=2
    

enter start, stop: 2,34
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34


### Display numbers from 100 to 110


In [250]:
x= 100
for i in range(100,111):
    print(i)

100
101
102
103
104
105
106
107
108
109
110


In [251]:
x=100
for i in range(100,110,2):
    print(i)
    
    

100
102
104
106
108


In [254]:
x=100
for i in range(100,111):
    for k in range(2,i):
        if i%k !=0:
            print(i)
      

100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
101
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102
102


### 15. To display Letters of a String

In [255]:

st = 'sai vinay sunkara'
for i in st:
    print(i)

s
a
i
 
v
i
n
a
y
 
s
u
n
k
a
r
a


In [256]:
for i in s:
    print(i)

s
i
d
d
u
 
b
a
b
u


#### 16. To find sum of list of numbers


In [257]:
lst = [10, 12, -15, -12, 15]
sum=0 

for i in lst:
    sum+=i
print('sum =', sum)

sum = 10
sum = 22
sum = 7
sum = -5
sum = 10


#### 17.  To display a multiplication table


In [258]:
x = int(input('which table you want me to Print?  - '))
for i in range(1, 21):
    print(i, 'x', x, '=',i*x)

which table you want me to Print?  - 3
1 x 3 = 3
2 x 3 = 6
3 x 3 = 9
4 x 3 = 12
5 x 3 = 15
6 x 3 = 18
7 x 3 = 21
8 x 3 = 24
9 x 3 = 27
10 x 3 = 30
11 x 3 = 33
12 x 3 = 36
13 x 3 = 39
14 x 3 = 42
15 x 3 = 45
16 x 3 = 48
17 x 3 = 51
18 x 3 = 54
19 x 3 = 57
20 x 3 = 60


### 18. check whether an element exits in a list or Not

In [268]:
lst = [12, 13, 14, 18, 22, 74, 89]
s= int(input('which element to search? ' ))
for i in lst:
    if s==i:
        print(' searched element',s,'exists in list')
        
else:
        print(' searched element',s,'doesnot exists in list')

which element to search? 89
 searched element 89 exists in list


#### 19. Tobreak a loop at 5

In [280]:
x = 0
while x<=10:
    x+=1
    if x==6:
         break
    print(x)
           

1
2
3
4
5


### 20 not to display from 5 onwards

In [281]:
x = 0
while x<=10:
    x+=1
    if x>=5:
        continue
    print(x)    

1
2
3
4


### 21. To retrive only Negative Numbers from the list

In [289]:
ls = [10, 12, -13, -14, 18, -19, 22, -23]
print(ls)
for i in ls:
    if(i>0):
        pass
    else:
        print(i)

[10, 12, -13, -14, 18, -19, 22, -23]
-13
-14
-19
-23


#### 22. Function to return sum value
#####     # Defining the Function

In [290]:
def sum(a,b):
    c=a+b
    return c


###### call the above function

In [292]:
res1 =sum(5, 10)
res2 = sum(10.5, 12.6)
print('result-1 = ', res1)
print('result-2 = ', res2)

result-1 =  15
result-2 =  23.1


### 23. Understanding the assert statements
###### #Assert Statement:   to check if a particular condition is fullfilled or not. if the condition fails, it displays the assert statement and also raises AssertionError

#### assert condition, 'message'

### Prog: - Check if user entered a number greater than 10 or not.

In [300]:
x= int(input('enter a number: '))
assert x>10, "wrong input"

print('you entered: ', x)

enter a number: 5


AssertionError: wrong input

### 24. Command Line Args

#####  The arguments passed to a python program at command prompt. they are stored in the form of a list in argv defined in 'sys' module.  

#### len(sys.argv) gives number of command line args.
##### sys.argv is a list that contains all command line args
###### sys.argv[0] contains the program name

In [301]:
import sys
# find the number of args
n= len(sys.argv)
print('no of args= ', n)

no of args=  3


In [302]:
# get all theargs
lst = sys.argv
print('they are: ')
for i in lst:
    print(i)

they are: 
C:\Users\sai vinay sunkara\anaconda3\lib\site-packages\ipykernel_launcher.py
-f
C:\Users\sai vinay sunkara\AppData\Roaming\jupyter\runtime\kernel-9d4d0497-35bc-4805-9fe6-454200d0797d.json


In [303]:
# show the program name
print('program name=', sys.argv[0])

program name= C:\Users\sai vinay sunkara\anaconda3\lib\site-packages\ipykernel_launcher.py


### 25. Command line args

In [304]:
import sys
# find no. of args
n= len(sys.argv)
print('No of args =', n)

No of args = 3


In [309]:
# get args from [1] till end and add them
sum = 0 
lst = sys.argv
for i in range(1,n):
    sum += float(lst[i])
    
print('sum=', sum)
print('average= ',sum/n)

ValueError: could not convert string to float: '-f'

### 26. Function Defination



In [311]:
def sum(a,b):
    """ to find sum of two numbers"""
    c=a+b
    print('sum= ',c)
    
# call the function
sum(5,15)

# call again
sum('hello','friend')

sum=  20
sum=  hellofriend


### 27. Function Defination


In [312]:
def sum_sub(a,b):
    """to find results of addition and subtraction"""
    c=a+b
    d=a-b
    return c, d
# call the function
c, d= sum_sub(5,10)
print("results= {} and {}". format(c,d))

results= 15 and -5


In [19]:
### Exercise

# Clauculate the area of triangle using Herons formula - given the side


a ,b, c  = [float(i) for i in input('enter the sides of triangle a, b,c : ').split(',')]
p = (a+b+c)/2
Area = (p*(p-a)*(p-b)*(p-c))**0.5
print('Area of the triangle  %0.2f = ', Area)

enter the sides of triangle a, b,c : 1, 2, 6
Area of the triangle  %0.2f =  (4.705835796207353e-16+7.685213074469699j)


In [30]:
# get an Integer(n) from the user, perform the following conditional actions with given list(l1)

l1 = [10, 977, 2557, 569, 547, 1478, 3365, 7843, 1, 546, 589, 7851, 454, 454, 441, 7458, 9658, 4125, 521, 565, 321, 5454, 12546]
a = float(input('enter the number to check = '))
for i in l1:
    if(a >10000 ):
        print('entered',a,'is GREATER THAN 10K')
        break
    else:     
        if(a%2!=0 and a not in l1):
            print('Great')
            break
        elif(a%2!=0 and  a in l1):
            print('Not Great')
            break
        elif(a%2==0 and a in l1 ):
            print('Great')
            break
        elif(a%2==0 and  a not in l1):
            print('Not Great') 
            break
        else:
            print('Try again')



enter the number to check = 124556
entered 124556.0 is GREATER THAN 10K


### 28. Function to return several values

In [32]:
def fun(n1,n2):
    a= n1+n2
    b= n1-n2
    c=n1*n2
    d= n1/n2
    return a, b, c, d
# call the function 
tp = fun(8,9)
print(tp)

for i in tp: print(i)

# check 2
pp = fun(7,8)
print(pp)

for i in pp: print(i)

(17, -1, 72, 0.8888888888888888)
17
-1
72
0.8888888888888888
(15, -1, 56, 0.875)
15
-1
56
0.875


### 29. Enter a Groupof numbers from Keyboard and Sorting them using a function


In [38]:
def sortnum(lst):
    lst.sort()
    for i in lst:print(i)
        
# take a group of numbers from keyboard
print('enter the numbers:')
lst =[float(x) for x in input().split(',')]

# call the function
sortnum(lst)


enter the numbers:
12,25,32,45,55
12.0
25.0
32.0
45.0
55.0


### 30.  Create a local variable and global variable and display their values

In [42]:
a= 5 # global variable
def fun():
    a=6 # local variable
    print('local variable : ', a)
    
fun()
print(a) # displays global variable


local variable :  6
5


### 31. use globals() to retrieve the global variable inside a function.

In [44]:
a= 5 # global variable
def fun():
    a=6 # local variable
    print('local variable : ', a) # displays a local variable
    
    x = globals()['a']
    print(' displays the global variable : ', x)
    
    
fun()
print(a)
    

local variable :  6
 displays the global variable :  5
5



 Functions are first class objects -
 
 This is means we can use the functions exactly as objects.
 
     it is possible to assign a function to a variable
     it is possible to define a function inside another function
     it is possible to pass a function as parameter to another function
     its possible that a function can return another function

#### 32.  Assign a function toa variable

In [45]:
def display(str):
    return 'hai' + str

var = display('krishna')
print(var)

haikrishna


#### 33. Define message() function inside display() function.

In [46]:
def display(str):
    def message():
        return 'how are you?'
    result = message()+str
    return result

var = display('krishna')
print(var)


how are you?krishna


#### 34. Pass message() to display() function as parameter

Function can be passed as parameters to other functions

In [48]:
def display(fun):
    return 'how are u? '+ fun
def message():
    return 'krishna'
var = display(message())
print(var)

how are u? krishna


#### 35. Return message() function from display() function.

Functions can return other functions

In [50]:
def display():
    def message():
        return 'how are you ?'
    return message

# call display() function and it returns message() function
# in the following code, var refers to the name: message.

var = display()
print(var())

how are you ?


##### Pass by Object reference.

pass by value and pass by reference are not valid in python. in python, values are passed to function by object references.
immutable objects: integers, floats, strings, tuples
Mutable objects; list and dictionaries are mutable
if the object is mutable, the modified value is not available outside the function and if the object is mutable, its modified version is available outside function

### 36. Pass a string to a function and modify it inside the function. display it outside the function after modification.

In [51]:
def modify(str):
    str = 'Hello' + str
    print(str, id(str))
    
# call modify() and pass str 
str = 'raju'
modify(str)
print(str, id(str))

Helloraju 2971468958896
raju 2971468958000


#### 37. Pass a [ list ] to a function and modify it inside the function. display it outside the function after modification

In [53]:
def modify(lst):
    lst. append(9)
    print (lst, id(lst))
    
# call modify( ) and pass lst
lst = [1,2,3,4,5,6,7,8,9]
modify(lst)
print(lst, id(lst))


[1, 2, 3, 4, 5, 6, 7, 8, 9, 9] 2971468948928
[1, 2, 3, 4, 5, 6, 7, 8, 9, 9] 2971468948928


## Recursive Function:

A function calling itself repeatedly

#### 38. Using recursion, caluculate factorial value of a given number

In [58]:
def factoal(n):
    if n==0:
        result = 1
    else:
        result = n*factoal(n-1)
    return result

n = int(input('enter a number: '))
print('Factorial of',n,'is =', factoal(n))

enter a number: 8
Factorial of 8 is = 40320


##### Function Decorators

A function decorator is a function that accepts a function as parameter and returns a function. A decorator takes the result of a function, modifies the result and returns it. thus decorators are useful to perform some additional processing required by a function

#### 39. Write a decorator function to increase the value by 2. 

In [60]:
def decor(fun):
    def inner():
        value = fun()
        return value+2
    return inner
""" 
# This is the function to which decorator should be applied
def num():
    return 10

result = decor(num)
print(result())

"""
@decor
def num():
    return 10
print(num())


12


In [61]:
@decor
def num():
    return 35
print(num())

37


#### 40. generator that returns sequence from X to Y

##### Generators:
Generators are functions that return a sequence of numbers.  A generator function is written like an Ordinary function but it uses 'yeild' statement. This statement is useful to return the value.

In [68]:
def mygen(x,y):
    while x<=y:
        yield x
        x+=1
        
# fill generator object with 5 and 10.
g = mygen(5, 10)

# Display all numbers in the generator
for i in g:
    print(i, end= '')

5678910

### Creating Our own Modules In Python

A Module represents a group of classes, methods, functions andvariables. In python we have several built-in modules like sys, io, time etc. just like these modules, we can also create our own modules and use them whenever we need them. once a module is created, any programmer in the project team can reuse that module. Hence, modules will make software development easy and faster.

#### 41. Create " MyModule " addtion and subtraction functions and use them in another program.

In [70]:
def add(a,b):
    print(a+b)
    
def sub(a, b):
    print(a-b)

    # the above program can be saved in the notebook
# save this as mymodule.py
import mymodule
x,y = [int(x) for x in input('enter two nos: ').split()]
mymodule.add(x,y)
mymodule.sub(x,y)

ModuleNotFoundError: No module named 'mymodule'

##### The special variable __name__

when a program is executed in python, there is a special variable internally created by the name '__name__'. This variable stores information regarding whether the program is executed as an individual program or as a module. when the program is executed directly, the python interpreter store the value '__main__' into this variable. when the program is imported as a module into another program, then python interpreter stores the module name into this variable. thus, by observing the value of the variable '__name__' , we can understand how the program is executed


#### 42. Create 'one' module with display() function. Find out how it is executed.

###  LAMBDAS or Anonymous Functions
A function without a name is called ' anonymuous function'. so far, the functions we worte were defined using the keyword 'def'. but anonymous functions are not defined using 'def'. they are defined using the keyword lambda and hence they are also called 'lambda Functions'.

#### 43. Create a lambda function to find square value of a number.

In [72]:
f= lambda x: x*x
    
value =f(5)
print('square of 5 =', value)

square of 5 = 25


#### 44. write a lambda to test weather a given number is enven or not


In [74]:
f= lambda x: 'yes' if x%2==0 else 'No'
value= f(18)
print(value)

yes


#### 45.  lambda function that returns even numbers from alist


In [75]:
lst= [45,22,15,1,3,2,28,24,2,26,7,78,98,95,94,96]
lst1 = list(filter(lambda x: (x%2 == 0), lst))
print(lst1)


[22, 2, 28, 24, 2, 26, 78, 98, 94, 96]


#### 46. create a lambda function to return squares of all the elements in a list

In [76]:
lst= [45,22,15,1,3,2,28,24,2,26,7,78,98,95,94,96]
lst1 = list(map(lambda x: x*x, lst))
print(lst1)

[2025, 484, 225, 1, 9, 4, 784, 576, 4, 676, 49, 6084, 9604, 9025, 8836, 9216]


#### 47. Lambda that returns product of the elements of a list

In [2]:
from functools import *
lst= [45,22,15,1,3,2,28,24,2,26,7,78,98,95,94,96]
result = reduce(lambda x, y: x*y, lst)
print(result)

142820888672157696000


#                                        ARRAYS

An Array is an object that stores a group of elements (Or values) of same datatype. Array elements should be of same datatype. Arrays can increase or decrease or decerese their size dynamically.


###### Note : we can use for loop to display the individual elements of the array. 

##### 48. Create different types of 1D arrays using numpy

In [1]:
import numpy
arr1 = numpy.array([1,2,3,4,5,6])
print(arr1)

arr2 = numpy.array([1.5,2.5,-3.44])
print(arr2)

arr3 =numpy.array(['a','b','c'])
print(arr3)

arr4 = numpy.array(['anil', 'gopal'])
print(arr4)

[1 2 3 4 5 6]
[ 1.5   2.5  -3.44]
['a' 'b' 'c']
['anil' 'gopal']


##### 49. creating an array using linspace()

In [4]:
from numpy import*
# divide 0-10 into 5 parts and take those points in the array

a= linspace(0,10,5)
print('a =' ,a)

a = [ 0.   2.5  5.   7.5 10. ]


#### 50. creating an array using logspace()

In [5]:
from numpy import *

# divide 1 power 10 to 4 power 10 into 5 equal parts
# and take those points in the array

a = logspace(1,4,5)

# display the elements of a 
for i in a : print(i, end =',')

10.0,56.23413251903491,316.22776601683796,1778.2794100389228,10000.0,

#### 51. Creating an array with even numbers up to 10



In [9]:
from numpy import*
# create an array using arrange() function

a= arange(2,11,2)
print(a)

b= arange(2,12,2)
print(b)

c= arange(2,13,2)
print(c)

[ 2  4  6  8 10]
[ 2  4  6  8 10]
[ 2  4  6  8 10 12]


##### 52. Create a 1D array using arange() and then create another array by alias, view and copy

In [12]:
# aliasing , viewing and copying an array.

from numpy import*
a=arange(1,6) # create array a
b=a             # b is alias to a 
# b= a.view()   # b is a shallow copy of a
# b=a.copy()    # b is deep copy of a

print('original array: ', a)
print('Alias array:', b)

b[0]=99  # modification of 0th element of b
print('after modification:')
print('original Array: ', a)
print('alias array: ',b)

original array:  [1 2 3 4 5]
Alias array: [1 2 3 4 5]
after modification:
original Array:  [99  2  3  4  5]
alias array:  [99  2  3  4  5]


#### 53. Create and display a 2D array

In [13]:
import  numpy
arr= numpy.array([[1,2,3] , [4,5], [10,11,12]])

# display only rows
for i in range(len(arr)):
    print(arr[i])
    
# display all elements
for i in range(len(arr)):
    for j in range(len(arr[i])):
        print(arr[i][j], end='')
    print()    

[1, 2, 3]
[4, 5]
[10, 11, 12]
123
45
101112


C:\Users\SAIVIN~1\AppData\Local\Temp/ipykernel_17972/1809494990.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr= numpy.array([[1,2,3] , [4,5], [10,11,12]])


#### 54. Matrix operation

In [14]:
import numpy as np
a= np.matrix([[1,2],[3,4]])
b = np.matrix([[2,2],[4,4]])

c= a*b
print(c)

d= a/2
print(d)

[[10 10]
 [22 22]]
[[0.5 1. ]
 [1.5 2. ]]


#### 55. Finding the transpose

In [17]:
import numpy
r,c = [int(a) for a in input('how many rows cols?').split(' ')]
str = input('enter elements:\n')

m = numpy.matrix(str)
x= numpy.reshape(m,(r,c))
print('original\n', x)
print('transpose\n', x.transpose())

how many rows cols?1 2
enter elements:
1,2
original
 [[1 2]]
transpose
 [[1]
 [2]]


#### 56. Finding transpose - to accept elements in matrix from


In [21]:
import numpy 
r,c = [int(a) for a in input('how many rows cols?').split(' ')]

arr= numpy.zeros((r,c))   # create a rXc 2D array

print('enter elements:')
for i in range(r):  # enter one row at a time
    arr[i] =[float(x) for x in input().split('')]
    
m = numpy.matrix(arr)
print('original\n', x)
print('transpose\n', x.transpose())


how many rows cols?1 2
enter elements:
1.2 12.3


ValueError: empty separator

#### 57.  Nested list with names and marks

In [22]:
lst = ['raju', [40,20,60], 'vani',[60,50,60],'kamal',[54,22,36]]
name = input('enter name:')
for i in range(len(lst)):
    if lst[i]== name:
        print('hai', name, end= '')
        print('your marks:' , end='')
        for x in lst[i+1]:
            print(x, end='')
        break 
else:
    print('name not found')

enter name:vani
hai vaniyour marks:605060

#### 58. List comprehension to get even nos upto 10

In [23]:
evens1 = [x for x in range(2, 11, 2)]
evens2 = [x for x in range(2, 11) if x%2 ==0]

print(evens1)
print(evens2)

[2, 4, 6, 8, 10]
[2, 4, 6, 8, 10]


#### 59 . Adding the elements of two lists


In [24]:
x= [10,20,30]
y=[10,50,80]

# with using the list comprehension
z= []

for i in range(len(x)):
    z.append(x[i]+y[i])
    
print(z)

# now using list comprehension
z = [x[i]+y[i] for i in range(len(x))]
print(z)

[20, 70, 110]
[20, 70, 110]


#### 60. To retrive common elements of two lists


In [25]:
x = [10,20,40,-1,20]
y= [40,50,20,-1,0]

# without using list comprehension
z=[]

for i in x:
    if i in y:
        z.append(i)
        
print(z)

# now using list comprehension
z = [ i for i in x if i in y]
print(z)        

[20, 40, -1, 20]
[20, 40, -1, 20]


#### 61.  To retrive only te first letter of each word in the words

In [28]:
words =['apple', 'grapes', 'banana']

# without using list comprehension
lst = []
for i in words:
    lst.append(i[0])
    
print(lst) 


# while using the List comprehension
lst = [i[0] for i in words]
print(lst)

['a', 'g', 'b']
['a', 'g', 'b']
